name: testsuite

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alt:sisyphus

    env:
      BUILDER: builder
      ALLOW_ROOT_USER: 1

    steps:
      - name: install packages
        run: |
            apt-get update && apt-get -y install etersoft-build-utils su sudo

      - uses: actions/checkout@v2

      - name: build
        run: |
            echo "%_allow_root_build 1" > ${HOME}/.rpmmacros
            rpmbb

      - name: install
        run: |
            apt-get install -y /usr/src/RPM/RPMS/noarch/*.rpm

      - name: testsuite
        run: |
            echo "testsuite.."
