name: testsuite

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alt:sisyphus

    env:
      BUILDER: builder

    steps:
      - name: install packages
        run: |
            apt-get update && apt-get -y install su sudo

      - uses: actions/checkout@v2

      - name: testsuite
        run: |
            echo "testsuite.."
