name: testsuite

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alt:sisyphus

    steps:
      - name: install packages
        run: |
            apt-get update && apt-get -y install etersoft-build-utils su sudo git-core
      - uses: actions/checkout@v2

      - name: build
        run: rpmbb

      - name: testsuite
        run: |
            cd testsuite;
            make check
